version: "3.7"
services:
  ignite:
    container_name: ignite-prisma
    hostname: ignite
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ignite
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5440:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - ignite-network

networks:
  ignite-network:
    name: ignite-network
    driver: bridge
